/** @type {import('tailwindcss').Config} */
// 这里只做「语义类名 → design token」的映射，具体数值全部在
// src/renderer/src/styles/theme.css（唯一真相源），组件里不允许再出现硬编码色值。
module.exports = {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        sidebar: 'var(--color-sidebar)',
        card: 'var(--color-card)',
        line: 'var(--color-border)',
        ink: 'var(--color-ink)',
        'ink-soft': 'var(--color-ink-soft)',
        muted: 'var(--color-muted)',
        'muted-soft': 'var(--color-muted-soft)',
        hover: 'var(--color-hover)',
        'hover-strong': 'var(--color-hover-strong)',
        overlay: 'var(--color-overlay)',
        accent: 'var(--color-accent)',
        'accent-soft': 'var(--color-accent-soft)',
        'accent-line': 'var(--color-accent-line)',
        'on-solid': 'var(--color-on-solid)',
        danger: 'var(--color-danger)',
        ok: 'var(--color-ok)',
        'file-ppt': 'var(--color-file-ppt)',
        'file-doc': 'var(--color-file-doc)',
        'file-xls': 'var(--color-file-xls)',
        'file-pdf': 'var(--color-file-pdf)',
        'file-md': 'var(--color-file-md)',
        'file-other': 'var(--color-file-other)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        serif: 'var(--font-serif)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        display: 'var(--text-display)',
      },
      lineHeight: {
        base: 'var(--leading-base)',
        tight: 'var(--leading-tight)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        input: 'var(--radius-input)',
        full: 'var(--radius-full)',
      },
      spacing: {
        sidebar: 'var(--size-sidebar)',
        'artifact-panel': 'var(--size-artifact-panel)',
        tree: 'var(--size-tree)',
        input: 'var(--size-input)',
        modal: 'var(--size-modal)',
        'graph-panel': 'var(--size-graph-panel)',
        'home-top': 'var(--home-top)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        pop: 'var(--shadow-pop)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
      },
    },
  },
  plugins: [],
}
